seed_everything: 42

trainer:
  precision: 32
  num_sanity_val_steps: 4
  accumulate_grad_batches: 1
  max_epochs: 1000
  strategy: ddp_find_unused_parameters_true
  default_root_dir: /import/c4dm-datasets-ext/tempnetic-logs # dir needs to already exist
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: tempnetic
      log_model: false
      save_dir: /import/c4dm-datasets-ext/tempnetic-logs
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_last: true
        save_top_k: 1
        monitor: val_accuracy_epoch
        filename: "{epoch}-{step}"
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: tempnetic.callbacks.MoveConfigCallback
    - class_path: tempnetic.callbacks.XYPlotCallback
  # enable_checkpointing: true