model:
  class_path: tempnetic.system.System
  init_args:
    lr: 0.0003
    weight_decay: 0.0001
    min_bpm: 40
    max_bpm: 250
    use_tempogram: True

    model:
      class_path: tempnetic.models.mobilenet.SpectrogramMobileNetV2
      init_args:
        embed_dim: 1
        sample_rate: 22050
        window_length: 1024
        hop_length: 512
        mel_bins: 64
        fmin: 50
        fmax: 11025